networks:
  localdev:
    name: localdev

services:
  api:
    container_name: graphql-api
    image: graphql-api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "6060:6060"
    depends_on:
      - db
    networks:
      - localdev
    environment:
      DBHOST: db
      ASPNETCORE_ENVIRONMENT: Development
      APP_CONNECTIONSTRING: "Host=db; Database=OrdersDB; Uid=postgres; Pwd=postgres"
  
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: graphql-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - localdev
#    volumes:
#      - ./pgdata:/var/lib/postgres/data